# Generated by Django 3.2.8 on 2021-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('Игры', 'Игры'), ('ОС', 'ОС'), ('Техника', 'Техника'), ('Безопасность', 'Безопасность'), ('Социальные сети', 'Социальные сети'), ('Автомобили', 'Автомобили')], default='', max_length=100),
        ),
    ]
