# Generated by Django 3.2.8 on 2021-11-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
